# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 88b8abf36bd42d4ca6d0b7de815e6a67ee95785ae33e1bece7c0ca5de6d151d283b64a16bb401c59faf4d60cc3ae35575f910f4016390a9ddc25c17aced2168c

test:
  secret_key_base: 23a6b41ba76822ca1c707b43742c72f5df08bfa55c76d6d733eb91a119a3e8788cd535b7643f4b1926c916113fdcf0d9fa4f0004c1fe368bf491b6b76e425cf5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
